### ISSUE TITLE
Umsetzung des Leidener Klammersystems

### ISSUE THREAD

**Issue by SvenjaBer** [stibi-sg/wiborada#3]
im Speziellen spitze Klammern im lat. Text, z. B. S. 40/S. 50.

Vorschlag zu S. 40, Kap. VI (5):
`<app>`
     `<lem><note>non</note>nullam</lem>`
          `<rdg wit="#S #A #Boll">nullam</rdg>`
          `<rdg wit="#A"><note>postea delevit</note></rdg>`
          `<rdg source="#Berschin">nonnullam</rdg>`
`</app>`

**Comment by ottosmops** [comment]
Eigentlich müsste es genügen wenn wir es so machen. Ist das noch valide? vgl. https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-supplied.html

```xml
<app>
  <lem><supplied>non</supplied>nullam</lem>
  <rdg wit="#S #A #Boll">nullam<note>codd.</note>
  <rdg wit="#A"><note>postea delevit.</note></rdg>
</app>
```
Was mein "codd."? 

Ist denn damit klar, wie es genau in den Einzelnen Textzeugen aussieht? Was wurde in A später gestrichen? Das non oder nonnullam oder das nullam?

Könnten wir, wenn wir A hätten evtl. genauer machen.

**Comment by SvenjaBer** [comment]
So ist es noch valide. 

Codd., also Codices, fasst einfach nur alle Handschriften, S, A und Boll., zusammen, der note Teil ist deswegen überflüssig. Ich gehe davon aus, dass in A dann später das nullam gestrichen wurde (hat wahrscheinlich keinen Sinn ergeben ohne das non). 

Danke!

**Comment by ottosmops** [comment]
Da die Edition von Berschin ist, müssen wir bei supplied nichts angeben. Wenn wir dann Berschin korrigieren, könnte man `@resp="sb"` o.ä. ergänzen.

**Comment by ottosmops** [comment]
Noch korrekter wäre es dann mit `<del></del>` zu arbeiten: https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-del.html
```xml
<app>
  <lem><supplied>non</supplied>nullam</lem>
  <rdg wit="#S #Boll">nullam</rdg>
  <rdg wit="#A"><del>nullam</del><note>postea delevit.</note></rdg>
</app>
```

Das weicht allerdings leicht vom Druck ab. Wäre aber digitaler. Lass uns mal bei der obigen Variante bleiben.
