### ISSUE TITLE
Überschneidung von Zitat und Fußnote

### ISSUE THREAD

**Issue by SvenjaBer** [stibi-sg/wiborada#5]
Z. B. Kap. XII: Das Zitat (cf. Eph 6,16) reicht von _Quę omnia ... gladioque <spiritus armata>_  und die Fußnote umfasst _gladioque <spiritus armata> signaculo_.

**Comment by wolfgangmm** [comment]
```xml
uarias terrorum
               figuras nefanda arte subdoloque commento in semet transfiguratas ei obiciens · <seg
                  type="cf." source="#Eph_6.16">Quę omnia machinamenta diaboli illa inexpugnabili
                  scuto non fictę fidei protecta gladioque <supplied>spiritus
                  armata</supplied></seg> · <app>
                  <lem>signaculo</lem>
                  <rdg wit="#S">gladioque signaculi</rdg>
                  <rdg wit="#A">gladioque signaculo</rdg>
                  <rdg wit="#Boll"><note>ex Herimanni vita c. 9 locum sanaverunt</note></rdg>
               </app> crucis inperterrita bellatrix deiecit · Et ut ea quę generaliter complexa sunt
               · singillatim auctoritate ueritatis aliqua ex parte proferam · quadam nocte dum
               solito more ad ęcclesiam properaret 
```

vs

```xml
uarias terrorum
               figuras nefanda arte subdoloque commento in semet transfiguratas ei obiciens · 
<seg type="cf." source="#Eph_6.16">Quę omnia machinamenta diaboli illa inexpugnabili
                  scuto non fictę fidei protecta gladioque <supplied>spiritus
                  armata</supplied>
<app>
                  <lem></lem>
                  <rdg wit="#S">gladioque</rdg>
                  <rdg wit="#A">gladioque</rdg>
                  <rdg wit="#Boll"></rdg>
               </app>
</seg>.
<app>
                  <lem>signaculo</lem>
                  <rdg wit="#S">signaculi</rdg>
                  <rdg wit="#A">signaculo</rdg>
                  <rdg wit="#Boll"><note>ex Herimanni vita c. 9 locum sanaverunt</note></rdg>
               </app> 
crucis inperterrita bellatrix deiecit · Et ut ea quę generaliter complexa sunt
               · singillatim auctoritate ueritatis aliqua ex parte proferam · quadam nocte dum
               solito more ad ęcclesiam properaret 
```

**Comment by SvenjaBer** [comment]
Könnte man so im ersten Apparat nicht den ganzen `gladioque <supplied>spiritus armata</supplied>` Teil ins Lemma nehmen? 

Und das `<rdg wit="#Boll"></rdg>` muss da leer stehen, damit man erkennen kann, dass sich die im zweiten Apparat genannte Lesart auch diese Stelle bezieht, verstehe ich das richtig?

Danke!

**Comment by ottosmops** [comment]
Ja das erscheint mir besser:
```xml
<p>
            <seg type="cf." source="#Eph_6.16">Quę omnia machinamenta diaboli illa inexpugnabili scuto non fictę fidei protecta 
               <app>
                  <lem>gladioque <supplied>spiritus armata</supplied></lem>
                  <rdg wit="#S">gladioque</rdg>
                  <rdg wit="#A">gladioque</rdg>
                  <rdg wit="#Boll"></rdg>
               </app>
            </seg>.
            
            <app>
               <lem>signaculo</lem>
               <rdg wit="#S">signaculi</rdg>
               <rdg wit="#A">signaculo</rdg>
               <rdg wit="#Boll"><note>ex Herimanni vita c. 9 locum sanaverunt</note></rdg>
            </app> 
         </p>
```

Was steht denn in Boll?

**Comment by SvenjaBer** [comment]
Die Bollandisten haben den Text, der in der Edition steht (tatsächlich das _spiritus armata_ dort auch in eckigen Klammern), und in der Fussnote wird angemerkt, dass sie den Text gemäss Kapitel 9 aus Herimanns Vita "geheilt" bzw. wiederhergestellt haben.

**Comment by ottosmops** [comment]
Ok dann müssten wir dort doch eigentlich das gleiche stehen haben wie in `<lem>`, ansonsten würde das bedeuten, dass Boll. da nicht stehen hat.

Neuer Versuch:

```xml
<p>
  <seg type="cf." source="#Eph_6.16">Quę omnia machinamenta diaboli illa inexpugnabili scuto non fictę fidei protecta 
               <app>
                  <lem>gladioque <supplied>spiritus armata</supplied></lem>
                  <rdg wit="#S">gladioque</rdg>
                  <rdg wit="#A">gladioque</rdg>
                  <rdg wit="#Boll">gladioque <supplied>spiritus armata</supplied><note>ex Herimanni vita c. 9 locum sanaverunt</note></rdg>
               </app>
            </seg>.
            
            <app>
               <lem>signaculo</lem>
               <rdg wit="#S">signaculi</rdg>
               <rdg wit="#A">signaculo</rdg>
            </app> 
</p>
```

**Comment by SvenjaBer** [comment]
Gut, dann würde ich als letztes noch sagen, dass man im zweiten Apparat entweder auch die Lesart von A weglässt oder oder auch dort nochmal die Boll-Lesart wie oben ergänzt, aber ich denke, ersteres sollte reichen. 
Wenn ich jetzt so darüber nachdenke, müsste es nicht auch im ersten Apparat so funktionieren?:

               <app>
                  <lem><supplied>spiritus armata</supplied></lem>
                  <rdg wit="#A #S"><note>deest</note></rdg>
                  <rdg wit="#Boll"><note>ex Herimanni vita c. 9 locum sanaverunt</note></rdg>
               </app>

**Comment by ottosmops** [comment]
Das letzte leere `<rdg>` bedeutet doch, dass da nichts ist (es ist ja nur die `<note>` drin)

- kein `<rdg>` => bedeutet, dass es keine Abweichung zum Text gibt
- leeres `<rdg>` => bedeutet "deest"

**Comment by SvenjaBer** [comment]
Also so?

`<rdg wit="#Boll"><supplied>spiritus armata<supplied><note>ex Herimanni vita c. 9 locum sanaverunt</note></rdg>`

**Comment by ottosmops** [comment]
Eigentlich braucht es den ersten Apparat nicht, denn gladioque haben ja alle:

```xml
<p>
  <seg type="cf." source="#Eph_6.16">Quę omnia machinamenta diaboli illa inexpugnabili scuto non fictę fidei protecta gladioque</seg>
  <app>
    <lem>signaculo <supplied>spiritus armata</supplied></lem>
    <rdg wit="#S">signaculi</rdg>
    <rdg wit="#A">signaculo</rdg>
    <rdg wit="#A">signaculo <supplied>spiritus armata</supplied><note>ex Herimanni vita c. 9 locum sanaverunt</note></rdg>
  </app> 
 </p>
```

**Comment by ottosmops** [comment]
Oder so:

```xml
<p>
  <seg type="cf." source="#Eph_6.16">Quę omnia machinamenta diaboli illa inexpugnabili scuto non fictę fidei protecta gladioque</seg>
  <app>
    <lem>signaculo>/lem> 
    <rdg wit="#S">signaculi</rdg>
    <rdg wit="#A">signaculo</rdg>
  </app> 
  <app>
    <lem><supplied>spiritus armata</supplied></lem>
    <rdg wit="#S #A"></rdg>
    <rdg wit="#Boll"><supplied>spiritus armata</supplied><note>ex Herimanni vita c. 9 locum sanaverunt</note></rdg>
  </app>
</p>
```

**Comment by SvenjaBer** [comment]
Den ersten Apparat braucht es aber doch, weil das _spiritus armata_ darein gehört. Das steht zwischen _gladioque_ und _signaculo_ und muss (meiner Meinung nach - es wäre Eph 6,18, obwohl Berschin nur 6,16 angibt) mit in das `<seg>`.

**Comment by ottosmops** [comment]
A sorry, aber dann einfach umdrehen und  für Eph 6,18 ein neues `<seg>` ?

**Comment by ottosmops** [comment]
Ne, macht auch keinen Sinn, nochmal sorry. Es ist ja "cf." und dann ist vermutlich die Erweiterung der Angabe auf Eph 6.16–18 besser. Jedenfalls ist das sowieso eine ziemlich lose Anspielung und nicht eigentlich ein Zitat. Ich würde das ja mit Eph. 6.10ff. beginnen lassen ("arma", "diaboli").

**Comment by SvenjaBer** [comment]
Ja genau, ich würde da auch einfach die Angabe erweitern auf Eph 6,11-17 (in meiner Ausgabe stehen _arma_ und _diaboli_ erst in 11 und ich hab mich eben vertan, deswegen 17 statt 18). Leider sind einige der Zitate nur solche losen Anspielungen, was es nicht unbedingt leicht macht, zu entscheiden, was worauf genau passen soll.
