### ISSUE TITLE
mehrere Parallelstellen zur selben Textstelle

### ISSUE THREAD

**Issue by SvenjaBer** [stibi-sg/wiborada#6]
Wenn mehrere Parallelstellen angegeben werden, die sich auf dieselbe Textstelle beziehen (z. B. Kap. XXV), während eine ein direktes Zitat, die andere indirekt zu vergleichen ist, wie kann man verdeutlichen, dass cf. nur auf eine source zu beziehen ist?
Z. B. Kap. XXV: _melius ei esset si natus non fuisset_ (Mt 26,24; cf. Mc 14,21)

**Comment by wolfgangmm** [comment]
```xml
<seg source="#Mt.26_24 #Mc.14_21"><note type="citation">Mt 26,24; cf. Mc 14,21</note>
melius ei esset si natus non fuisset 
</seg>
```

**Comment by ottosmops** [comment]
Die note ist nur nötig, wenn Du das abweichend vom Standard anzeigen lassen willst.
