### ISSUE TITLE
Korrekturen

### ISSUE THREAD

**Issue by SvenjaBer** [stibi-sg/wiborada#7]
Eintrag im Apparat z. B.: _ex_ adminuculo _corr. S_ (Kap. XXXIX)
Vorschläge:
```
<app> 
<lem>adminiculo</lem>
<rdg wit="#S" varSeq="1">adminuculo</rdg>
<rdg wit="#S" cause="korrigiert" varSeq="2">adminiculo</rdg> 
</app>

```
oder
```
<app>
<lem>adminiculo</lem>
<rdg wit="#S" varSeq="1">adminuculo</rdg>
<rdg wit="#S" varSeq="2">adminiculo</rdg>
<witDetail wit="#S"><mentioned>u</mentioned>corr.</witDetail>
</app>

```
Allerdings ist varSeq nicht valide und bei dem `<mentioned>u</mentioned>` wird m. M. n. nicht ganz klar, ob das der korrigierte oder der zu korrigierende Buchstabe sein soll. Wobei man ja am varSeq nachvollziehen kann, was die erste und was die zweite (korrigierte) Version ist.

**Comment by ottosmops** [comment]
`@varSeq` wäre bei tei_all vermutlich valide, könnte man also nehmen. Ich denke aber, dass es wäre einfacher ist, eine note zu machen.

```xml
<app> 
<lem>adminiculo</lem>
<rdg wit="#S">adminiculo<note>ex adminuculo corr.</note></rdg> 
</app>
```
Können und wollen wir später eine Anzeige programmieren, die `@varSeq` versteht? Wissen wir wer das wann korrigiert hat?

**Comment by SvenjaBer** [comment]
Der Schreiber hat sich meist direkt selbst korrigiert. 
An der Note-Version stört mich ein bisschen, dass sich das adminuculo nicht von dem ex und dem corr. abhebt wie im Druck durch die Kursivierung. Das würden die anderen Möglichkeiten präziser machen.

**Comment by ottosmops** [comment]
Ich bin da kein Fachmann, die Korrektur ist ja eine Radierung.

```xml 
<app> 
<lem>adminiculo</lem>
<rdg wit="#S">
  admin
  <subst>
    <del>u</del>
    <add>i</add>
  </subst>
  culo
</rdg>
</app>
```
Das wäre es dann vermutlich, was wir brauchen. Keine Ahnung, ob und wie wir das dann darstellen können. Vielleicht sicherheithalber noch eine note beifügen "«adminiculo» ex «adminuculo» corr." ?

**Comment by SvenjaBer** [comment]
Alles klar, so geht es.
