### ISSUE TITLE
Aufbau der zweiten Vita

### ISSUE THREAD

**Issue by SvenjaBer** [stibi-sg/wiborada#8]
Prolog und Kapitelverzeichnis können, denke ich, gut mit in den `<body>` integriert werden:
```
<teiHeader> ... </teiHeader>
<text>
 <body>
  <div type="prologue"> ... </div>
  <div type="contents">
   <head>CAPITULA LIBRI SEQUENTIS</head>
   <list>
    <item n="I">Quali parentela beata uuiborada originem duxit · et qualis eius conuersatio in annis infantię fuit ·<ptr 
     target="#vw2_I"/>
    </item>
    <item n="II">Quam laudabile sit nomen illius · <ptr target="#vw2_II"/>
    </item>
     ...
   </list>
  </div>
```
 Bei den einzelnen items könnte man statt `<ptr/>` auch mit `<ref/>` arbeiten, wie schon bei den Verweisen auf andere Kapitel im Text:

```
<item n="I">
<ref target="#vw2_I">Quali parentela beata uuiborada originem duxit · et qualis eius conuersatio in annis infantię fuit ·</ref>
</item>
```
Beides wäre valide.

**Comment by ottosmops** [comment]
Ich würde mal `<ref>` nehmen, so was kann man schnell auch automatisch ändern, falls es dann doch anders heissen soll. Allerdings würde ich das `<ref>` nicht leer lassen, sondern jeweils etwas umschliessen. Dann haben wir Text der zum Link umfunktioniert wird.
