### ISSUE TITLE
Liste der zitierten Handschriften

### ISSUE THREAD

**Issue by SvenjaBer** [stibi-sg/wiborada#9]
Hey,
ich wollte gerade die Witnesslisten aus den Dateien beider Viten zusammenfügen und die restlichen Handschriften ergänzen, die in der Liste der zitierten Handschriften (S. 237 im Druck) stehen. Dabei ist mir aufgefallen, dass ich teilweise in der ersten und der zweiten Vita die gleiche xml:id an verschiedene Textzeugen vergeben habe (in der Vita Ekkeharti ist die Augsburger Hs. "A", in der Vita Herimanni ist St. Gallen 560 "A") , was wahrscheinlich okay ist, solange es in der Datei der jeweiligen Vita bleibt, aber wenn ich jetzt die Liste zusammenführen will oder auch, wenn alles umgesetzt werden soll, ergibt es wohl Probleme, oder? 
Muss ich also jetzt für eine der beiden Handschriften überall die xml:id ändern oder gibt es da noch eine andere Möglichkeit? Vor allem, da die aktuellen xml:ids mit den Siglen im Druck übereinstimmen und so ja auch im Apparat auftauchen, wo sie möglichst so bleiben sollten.

PS: Die "Suchen und Ersetzen"-Funktion habe ich im Editor schon gefunden, aber dann würde er auch alle anderen Stellen ändern, an denen die xml:id mit "a" anfängt.

**Comment by ottosmops** [comment]
Sind die Daten schon in einer Datei? Ansonsten einfach in eine andere Datei nehmen und dort die Ersetzungen machen. Und wieder zurückkopieren. 

Oder Du gibst mir genau an, in welcher Datei genau was ersetzt werden soll, dann kann ich das machen.

**Comment by ottosmops** [comment]
Ausserdem dürfte es eigentlich keine Probleme geben: Wir belassen die beiden Viten in unterschiedlichen Dateien. Dann könntest Du in einer Gesamtliste mit dem Attribute `@corresp` arbeiten und `dateiname#xml:id`  verwenden um auf eine Handschrift zu verweisen, also z.B.: 

```
corresp="Ekkeharti_Vita_S_Wiboradae.xml#A"
```

**Comment by SvenjaBer** [comment]
Die zweite Möglichkeit klingt perfekt, danke!
